from DongliTeahousePySideWheel.demo.demoModule.DemoSettingPage import DemoSettingPage
from DongliTeahousePySideWheel.demo.demoModule.DemoCentralWidget1 import DemoCentralWidget1
from DongliTeahousePySideWheel.demo.demoModule.DemoMainWindow2 import DemoMainWindow2